In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
from pathlib import Path as P
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['KaiTi', 'SimHei', 'FangSong']  # 汉字字体,优先使用楷体，如果找不到楷体，则使用黑体
plt.rcParams['font.size'] = 12  # 字体大小
plt.rcParams['axes.unicode_minus'] = False  # 正常显示负号
from collections import defaultdict
import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle

## 获取数据集

这里是要把问题所需的训练数据整理出来，基本上就是一个机器学习的数据集获取的过程。

这是土壤湿度W，每月的数据。注意：代码里面用符号H表示，实际上是W。

In [11]:
df=pd.read_csv('问题2-原训练数据.csv',index_col='time',parse_dates=True)
df_raw=df
df

,10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),200cm湿度(kg/m2),土壤蒸发量(mm),降水量(mm),平均气温(℃)
time,,,,,,,
2012-01-01,13.73,30.87,42.79,168.56,0.61,2.29,-22.94
2012-02-01,13.00,30.87,42.79,168.56,0.86,2.29,-17.86
2012-03-01,12.60,30.87,42.79,168.56,1.91,21.84,-7.11
2012-04-01,11.97,30.73,42.76,168.56,7.20,6.10,6.94
2012-05-01,14.18,29.99,42.58,168.56,18.10,50.80,14.61
...,...,...,...,...,...,...,...
2021-11-01,13.91,52.17,93.43,164.49,1.44,530.86,-5.89
2021-12-01,13.14,52.14,93.45,164.48,0.93,193.80,-12.41
2022-01-01,12.45,52.14,93.45,164.48,0.44,607.31,-17.09
2022-02-01,12.10,52.14,93.45,164.48,0.27,796.04,-17.93
2022-03-01,14.96,52.13,93.44,164.48,5.98,115.57,-2.36

In [12]:
df=pd.read_csv('问题2-训练数据-归一化.csv',index_col='time',parse_dates=True)
scaler = pickle.load(P('问题2-MinMaxScaler-训练数据.pkl').open('rb'))
df

,10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),200cm湿度(kg/m2),土壤蒸发量(mm),降水量(mm),平均气温(℃)
time,,,,,,,
2012-01-01,-0.295198,-1.546133,-0.867652,1.378895,-0.954000,-0.551177,-1.850381
2012-02-01,-0.552436,-1.546133,-0.867652,1.378895,-0.928251,-0.551177,-1.493255
2012-03-01,-0.693388,-1.546133,-0.867652,1.378895,-0.820102,-0.413975,-0.737526
2012-04-01,-0.915388,-1.564934,-0.869724,1.378895,-0.275240,-0.524438,0.250195
2012-05-01,-0.136626,-1.664311,-0.882157,1.378895,0.847443,-0.210735,0.789399
...,...,...,...,...,...,...,...
2021-11-01,-0.231769,1.314318,2.630293,-2.804925,-0.868512,3.158313,-0.651759
2021-12-01,-0.503103,1.310290,2.631674,-2.815205,-0.921041,0.792835,-1.110118
2022-01-01,-0.746245,1.310290,2.631674,-2.815205,-0.971510,3.694837,-1.439124
2022-02-01,-0.869579,1.310290,2.631674,-2.815205,-0.989020,5.019339,-1.498176
2022-03-01,0.138231,1.308947,2.630984,-2.815205,-0.400899,0.243819,-0.403599

对变量进行最小最大值归一化（MinMaxScale），把变量的范围映射到0-1区间。

In [13]:
df['month']=df.index.month
df['year']=df.index.year-np.min(df.index.year)
df=df.sort_index(axis=1)
df.to_csv('问题2-训练数据-归一化-回归.csv')
df

,100cm湿度(kg/m2),10cm湿度(kg/m2),200cm湿度(kg/m2),40cm湿度(kg/m2),month,year,土壤蒸发量(mm),平均气温(℃),降水量(mm)
time,,,,,,,,,
2012-01-01,-0.867652,-0.295198,1.378895,-1.546133,1,0,-0.954000,-1.850381,-0.551177
2012-02-01,-0.867652,-0.552436,1.378895,-1.546133,2,0,-0.928251,-1.493255,-0.551177
2012-03-01,-0.867652,-0.693388,1.378895,-1.546133,3,0,-0.820102,-0.737526,-0.413975
2012-04-01,-0.869724,-0.915388,1.378895,-1.564934,4,0,-0.275240,0.250195,-0.524438
2012-05-01,-0.882157,-0.136626,1.378895,-1.664311,5,0,0.847443,0.789399,-0.210735
...,...,...,...,...,...,...,...,...,...
2021-11-01,2.630293,-0.231769,-2.804925,1.314318,11,9,-0.868512,-0.651759,3.158313
2021-12-01,2.631674,-0.503103,-2.815205,1.310290,12,9,-0.921041,-1.110118,0.792835
2022-01-01,2.631674,-0.746245,-2.815205,1.310290,1,10,-0.971510,-1.439124,3.694837
2022-02-01,2.631674,-0.869579,-2.815205,1.310290,2,10,-0.989020,-1.498176,5.019339
2022-03-01,2.630984,0.138231,-2.815205,1.308947,3,10,-0.400899,-0.403599,0.243819