In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from pathlib import Path as P
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['KaiTi', 'SimHei', 'FangSong']  # 汉字字体,优先使用楷体，如果找不到楷体，则使用黑体
plt.rcParams['font.size'] = 12  # 字体大小
plt.rcParams['axes.unicode_minus'] = False  # 正常显示负号
from collections import defaultdict
import plotly.express as px

In [2]:
# 因变量：200 的曲线基本没变化，随机数就行。
Y_COLS=['10cm湿度(kg/m2)', '40cm湿度(kg/m2)', '100cm湿度(kg/m2)',]
# 自变量：
X_COLS=['土壤蒸发量(mm)', '土壤蒸发量(W/m2)', '平均露点温度(℃)', '最低气温极值(℃)', '平均最低气温(℃)']

这里定义了3个因变量和5个自变量。其中200cm深度土壤湿度因为变化幅度很小（在个位及以下变化），
不需要预测，可以看做常量。

In [3]:
df_train=pd.read_csv('问题2-原始训练数据.csv')

In [4]:
df_train

,time,10cm湿度(kg/m2),40cm湿度(kg/m2),100cm湿度(kg/m2),土壤蒸发量(mm),土壤蒸发量(W/m2),平均露点温度(℃),最低气温极值(℃),平均最低气温(℃)
0,2012-01-01,13.73,30.87,42.79,0.61,0.57,-26.72,-35.61,-29.35
1,2012-02-01,13.00,30.87,42.79,0.86,0.86,-22.43,-34.89,-26.25
2,2012-03-01,12.60,30.87,42.79,1.91,1.78,-12.99,-27.28,-14.78
3,2012-04-01,11.97,30.73,42.76,7.20,6.94,-9.50,-8.50,-1.94
4,2012-05-01,14.18,29.99,42.58,18.10,16.89,-3.31,0.11,4.93
...,...,...,...,...,...,...,...,...,...
122,2022-03-01,14.96,52.13,93.44,5.98,5.58,-12.67,-20.50,-11.22
123,2022-04-01,NaN,NaN,NaN,NaN,NaN,-10.66,-9.39,-2.66
124,2022-05-01,NaN,NaN,NaN,NaN,NaN,-3.76,-4.50,3.09
125,2022-06-01,NaN,NaN,NaN,NaN,NaN,8.32,4.28,11.75
126,2022-07-01,NaN,NaN,NaN,NaN,NaN,10.63,12.22,15.34